apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployments.yaml

images:
  - name: <AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/iot-streaming-platform/ingestion-api
    newTag: latest
  - name: <AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/iot-streaming-platform/read-api
    newTag: latest
  - name: <AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/iot-streaming-platform/stream-processor
    newTag: latest
  - name: <AWS_ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/iot-streaming-platform/alerting-service
    newTag: latest
