apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingestion-api
  namespace: iot-streaming
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::130954244866:role/iot-streaming-ingestion-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stream-processor
  namespace: iot-streaming
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::130954244866:role/iot-streaming-stream-processor
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alerting-service
  namespace: iot-streaming
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::130954244866:role/iot-streaming-alerting-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: read-api
  namespace: iot-streaming
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::130954244866:role/iot-streaming-read-api
