apiVersion: v1
kind: Service
metadata:
  name: ingestion-api
  namespace: iot-streaming
spec:
  selector:
    app: ingestion-api
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: read-api
  namespace: iot-streaming
spec:
  selector:
    app: read-api
  ports:
    - port: 80
      targetPort: 3001
  type: ClusterIP
